//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersRehberi.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KonuAnlatimlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KonuAnlatimlari()
        {
            this.KonuAnlatimVerileri = new HashSet<KonuAnlatimVerileri>();
        }
    
        public int Id { get; set; }
        public int KonuId { get; set; }
        public int KonuAnlatimTurId { get; set; }
        public int OlusturanPersonelId { get; set; }
    
        public virtual KonuAnlatimTurleri KonuAnlatimTurleri { get; set; }
        public virtual Konular Konular { get; set; }
        public virtual Personeller Personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KonuAnlatimVerileri> KonuAnlatimVerileri { get; set; }
    }
}
