//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersRehberi.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.Testler = new HashSet<Testler>();
        }
    
        public int KisiId { get; set; }
        public string OkulNo { get; set; }
        public int SinifId { get; set; }
        public Nullable<int> VeliId { get; set; }
    
        public virtual Kisiler Kisiler { get; set; }
        public virtual Siniflar Siniflar { get; set; }
        public virtual Veliler Veliler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testler> Testler { get; set; }
    }
}
