//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersRehberi.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secenekler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Secenekler()
        {
            this.SecenekVerileri = new HashSet<SecenekVerileri>();
        }
    
        public int Id { get; set; }
        public int SoruId { get; set; }
        public int AnlatimTurId { get; set; }
        public string SecenekIsmi { get; set; }
    
        public virtual DogruSecenekler DogruSecenekler { get; set; }
        public virtual SecenekAnlatimTurleri SecenekAnlatimTurleri { get; set; }
        public virtual Sorular Sorular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecenekVerileri> SecenekVerileri { get; set; }
    }
}
