//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersRehberi.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinavlar
    {
        public int TestId { get; set; }
        public int OlusturanPersonelId { get; set; }
        public string SinavAdi { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public System.TimeSpan Sure { get; set; }
    
        public virtual Personeller Personeller { get; set; }
        public virtual Testler Testler { get; set; }
    }
}
