//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersRehberi.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sorular()
        {
            this.Secenekler = new HashSet<Secenekler>();
            this.SoruVerileri = new HashSet<SoruVerileri>();
        }
    
        public int Id { get; set; }
        public int DersId { get; set; }
        public int AnlatimTurId { get; set; }
        public int OlusturanPersonelId { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Personeller Personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Secenekler> Secenekler { get; set; }
        public virtual SoruAnlatimTurleri SoruAnlatimTurleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruVerileri> SoruVerileri { get; set; }
        public virtual TesteBagliSorular TesteBagliSorular { get; set; }
    }
}
